language: android
jdk:
  - oraclejdk9
sudo: false

android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29

# See https://stackoverflow.com/a/51644855/1831741 for the Java options
env:
  - FLAVOUR=testDebug
  - FLAVOUR=testRelease

script:
  - "./gradlew clean $FLAVOUR --console=plain"

notifications:
  email: false

before_install:
  - export JAVA_OPTS='--add-modules java.se.ee' && yes | sdkmanager "platforms;android-29"

# Caching according to the docs at https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

# We only build on these branches and on release tags, which are tagged r[0-9]+.
branches:
  only:
  - master
  - development
  - /^r\d+$/