language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - "./gradlew clean test"

notifications:
  email: false

sudo: false

cache:
  directories:
    - "$HOME/.gradle"

before_install:
  - openssl aes-256-cbc -K $encrypted_d5c31904a1d5_key -iv $encrypted_d5c31904a1d5_iv -in secrets.properties.enc -out ./app/secrets.properties -d
