# Common file with version numbers, used by the different subprojects
# Also used by the flake file to get the correct versions if you need it.
# IMPORTANT: this file is read as a "Java Properties file" by Gradle
#            AND as a "TOML file" by Nix. So it needs to be valid in both.
# Since properties strings are not quoted, we unquote the values in Gradle.
cmdLineToolsVersion = "12.0-rc15"
platformToolsVersion = "34.0.4"
buildToolsVersions = "34.0.0"
platformVersions = "34"
