package be.ugent.zeus.hydra.fragments.settings;

import android.app.LoaderManager;
import android.content.Loader;
import android.os.Bundle;
import android.preference.CheckBoxPreference;
import android.preference.PreferenceCategory;
import android.preference.PreferenceFragment;
import android.preference.PreferenceScreen;
import android.support.design.widget.Snackbar;
import android.view.View;
import be.ugent.zeus.hydra.HydraApplication;
import be.ugent.zeus.hydra.R;
import be.ugent.zeus.hydra.loader.ThrowableEither;
import be.ugent.zeus.hydra.fragments.settings.loader.CachedAsyncTaskLoaderSystem;
import be.ugent.zeus.hydra.models.association.Association;
import be.ugent.zeus.hydra.models.association.Associations;
import be.ugent.zeus.hydra.requests.AssociationsRequest;

import java.util.*;

/**
 * @author Rien Maertens
 * @since 16/02/2016.
 * <p>
 * <p>
 * SharedPreferences sharedPrefs = PreferenceManager.getDefaultSharedPreferences(getActivity()); boolean sf =
 * sharedPrefs.getBoolean("pref_association_checkbox", false);
 */
public class ActivityFragment extends PreferenceFragment implements LoaderManager.LoaderCallbacks<ThrowableEither<Associations>> {

    private static final int LOADER = 0;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Load the preferences from an XML resource
        addPreferencesFromResource(R.xml.activities);

        getLoaderManager().initLoader(LOADER, null, this);
    }

    @Override
    public void onResume() {
        super.onResume();

        HydraApplication happ = (HydraApplication) getActivity().getApplication();
        happ.sendScreenName("settings");
    }

    private void addPreferencesFromRequest(final List<Association> associations) {
        Set<String> set = new HashSet<>();
        PreferenceScreen target = (PreferenceScreen) findPreference("associationPrefListScreen");

        target.setTitle("Verenigingen");

        for (Association asso : associations) {
            PreferenceCategory parentCategory;
            if (!set.contains(asso.getParentAssociation())) {
                parentCategory = new PreferenceCategory(target.getContext());
                parentCategory.setKey(asso.getParentAssociation());
                parentCategory.setTitle(asso.getParentAssociation());
                target.addPreference(parentCategory);
                set.add(asso.getParentAssociation());
            }
            parentCategory = (PreferenceCategory) findPreference(asso.getParentAssociation());
            CheckBoxPreference checkBoxPreference = new CheckBoxPreference(target.getContext());
            checkBoxPreference.setKey(asso.getName());
            checkBoxPreference.setChecked(false);
            checkBoxPreference.setTitle(asso.getName());
            parentCategory.addPreference(checkBoxPreference);
        }
    }

    private void showFailureSnackbar() {
        assert getView() != null;
        Snackbar.make(getView(), "Oeps! Kon verenigingen niet ophalen.", Snackbar.LENGTH_LONG)
                .setAction("Opnieuw proberen", new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        getLoaderManager().restartLoader(LOADER, null, ActivityFragment.this);
                    }
                })
                .show();
    }


    /**
     * Instantiate and return a new Loader for the given ID.
     *
     * @param id   The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     *
     * @return Return a new Loader instance that is ready to start loading.
     */
    @Override
    public Loader<ThrowableEither<Associations>> onCreateLoader(int id, Bundle args) {
        return new CachedAsyncTaskLoaderSystem<>(new AssociationsRequest(), getActivity().getApplicationContext());
    }

    /**
     * @param loader The Loader that has finished.
     * @param data   The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(Loader<ThrowableEither<Associations>> loader, ThrowableEither<Associations> data) {
        if (data.hasError()) {
            showFailureSnackbar();
        } else {
            List<Association> associations = data.getData();
            Collections.sort(associations, new Comparator<Association>() {
                @Override
                public int compare(Association lhs, Association rhs) {
                    return lhs.getName().compareToIgnoreCase(rhs.getName());
                }
            });
            addPreferencesFromRequest(associations);
        }
    }

    /**
     * Called when a previously created loader is being reset, and thus making its data unavailable.  The application
     * should at this point remove any references it has to the Loader's data.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(Loader<ThrowableEither<Associations>> loader) {
        loader.reset();
    }
}