name: CI

# We run the tests on master, development and for PR's.
on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [testOpenDebug, testOpenRelease, testStoreDebug, testStoreRelease]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9
      - name: Cache Gradle files
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.command }}-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ matrix.command }}-${{ runner.os }}-gradle-
      - name: Test with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ matrix.command }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9
      - name: Cache Gradle files
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: lint-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            lint-${{ runner.os }}-gradle-
      - name: Lint with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: lint
